#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';

use Manzano\CvdwCli\Configurar;
use Manzano\CvdwCli\Opcoes;
use Manzano\CvdwCli\Executar;
use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\Console\Style\SymfonyStyle;

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

\Sentry\init([
    'dsn' => 'https://5a57b7ef5b7feaaeaca4a1db1c3fda4e@o4506804358414336.ingest.sentry.io/4506804360183808',
    // Specify a fixed sample rate
    'traces_sample_rate' => 1.0,
    // Set a sampling rate for profiling - this is relative to traces_sample_rate
    'profiles_sample_rate' => 1.0,
]);

salvarEnv();
retornarEnvs();

$app = new Application('Manzano // CVDW CLI', 'v1.0.0');
$app->add(new Opcoes());
$app->add(new Configurar());
$app->add(new Executar());
$app->setDefaultCommand('opcoes', false);
$app->run();