#!/usr/bin/env php
<?php
require_once __DIR__ . '/../vendor/autoload.php';
require_once __DIR__ . '/app/Inc/Conexao.php';

use Manzano\CvdwCli\Configurar;
use Manzano\CvdwCli\Opcoes;
use Manzano\CvdwCli\Executar;
use Manzano\CvdwCli\Services\Ambientes;

use Symfony\Component\Console\Application;

$ambienteObj = new Ambientes();
$ambienteObj->salvarEnv();
if(!$ambienteObj->retornarEnvs()){
    echo "Ambiente informado não foi encontrado.";
    exit;
}

$app = new Application('Manzano // CVDW-CLI', $ambienteObj->retornarVersao());
$app->add(new Opcoes());
$app->add(new Configurar());
$app->add(new Executar());
$app->setDefaultCommand('opcoes', false);
$app->run();
